//! Testimony wire protocol.
//!
//! Mirrors `go/protocol/protocol.go` and the `TESTIMONY_PROTOCOL_TYPE_*`
//! constants in `c/testimony.c`. Wire format:
//!
//! ```text
//! | 0 | 1 | 2 | 3 | 4 | 5 | 6 | ...
//! | type  | len   | value ....
//! ```
//!
//! `type` and `len` are big-endian `u16`s packed into a `u32`. The high bit
//! of `type` is always set for TLV messages, so a leading zero high-bit
//! identifies a bare `BlockIndex`.

#![no_std]

pub const PROTOCOL_VERSION: u8 = 2;

// These exact values are committed wire identifiers — they correspond
// to the constants in `c/testimony.c` (which were generated by
// `go/protocol/to_c` from the Go `iota` declarations). Changing any of
// them breaks every existing client. See parity audit notes in this
// crate's history.
pub const TYPE_BLOCK_INDEX: u16 = 0; // 0x0000
pub const TYPE_SERVER_TO_CLIENT: u16 = 32769; // 0x8001
pub const TYPE_WAITING_FOR_FANOUT_INDEX: u16 = 32770; // 0x8002
pub const TYPE_FANOUT_SIZE: u16 = 32771; // 0x8003
pub const TYPE_BLOCK_SIZE: u16 = 32772; // 0x8004
pub const TYPE_NUM_BLOCKS: u16 = 32773; // 0x8005
pub const TYPE_CLIENT_TO_SERVER: u16 = 49158; // 0xC006
pub const TYPE_FANOUT_INDEX: u16 = 49159; // 0xC007
pub const TYPE_ERROR: u16 = 65535; // 0xFFFF

// Compile-time anchors that match the values in `c/testimony.c`. These can
// never silently regress: if any constant changes, the crate stops compiling.
const _: () = assert!(TYPE_BLOCK_INDEX == 0);
const _: () = assert!(TYPE_SERVER_TO_CLIENT == 0x8001);
const _: () = assert!(TYPE_WAITING_FOR_FANOUT_INDEX == 0x8002);
const _: () = assert!(TYPE_FANOUT_SIZE == 0x8003);
const _: () = assert!(TYPE_BLOCK_SIZE == 0x8004);
const _: () = assert!(TYPE_NUM_BLOCKS == 0x8005);
const _: () = assert!(TYPE_CLIENT_TO_SERVER == 0xC006);
const _: () = assert!(TYPE_FANOUT_INDEX == 0xC007);
const _: () = assert!(TYPE_ERROR == 0xFFFF);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Category {
    BlockIndex,
    ServerToClient,
    ClientToServer,
    Error,
}

pub fn category_of(typ: u16) -> Category {
    if typ & 0x8000 == 0 {
        Category::BlockIndex
    } else if typ > TYPE_SERVER_TO_CLIENT && typ < TYPE_CLIENT_TO_SERVER {
        Category::ServerToClient
    } else if typ > TYPE_CLIENT_TO_SERVER && typ < TYPE_ERROR {
        Category::ClientToServer
    } else {
        Category::Error
    }
}

/// Pack a (type, length) pair into the on-wire `u32`.
#[inline]
pub fn to_tl(typ: u16, length: u16) -> u32 {
    ((typ as u32) << 16) | (length as u32)
}

/// Unpack an on-wire `u32` into a `(type, length)` pair.
///
/// When the high bit is unset, the value is a bare block index, not a TLV;
/// in that case this returns `(BlockIndex sentinel, 0)`.
#[inline]
pub fn tl_from(raw: u32) -> (u16, u16) {
    if raw & 0x8000_0000 == 0 {
        (TYPE_BLOCK_INDEX, 0)
    } else {
        ((raw >> 16) as u16, (raw & 0xFFFF) as u16)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Anchor against the decimal constants in `c/testimony.c` (lines
    /// generated by `go/protocol/to_c`). If any of these change, every
    /// existing client breaks.
    #[test]
    fn matches_c_generated_constants() {
        assert_eq!(TYPE_BLOCK_INDEX, 0);
        assert_eq!(TYPE_SERVER_TO_CLIENT, 32769);
        assert_eq!(TYPE_WAITING_FOR_FANOUT_INDEX, 32770);
        assert_eq!(TYPE_FANOUT_SIZE, 32771);
        assert_eq!(TYPE_BLOCK_SIZE, 32772);
        assert_eq!(TYPE_NUM_BLOCKS, 32773);
        assert_eq!(TYPE_CLIENT_TO_SERVER, 49158);
        assert_eq!(TYPE_FANOUT_INDEX, 49159);
        assert_eq!(TYPE_ERROR, 65535);
    }

    #[test]
    fn block_index_recognized() {
        assert_eq!(category_of(0), Category::BlockIndex);
        assert_eq!(category_of(0x7FFF), Category::BlockIndex);
        assert_eq!(tl_from(42), (TYPE_BLOCK_INDEX, 0));
    }

    #[test]
    fn server_to_client_range() {
        assert_eq!(
            category_of(TYPE_WAITING_FOR_FANOUT_INDEX),
            Category::ServerToClient
        );
        assert_eq!(category_of(TYPE_FANOUT_SIZE), Category::ServerToClient);
        assert_eq!(category_of(TYPE_BLOCK_SIZE), Category::ServerToClient);
        assert_eq!(category_of(TYPE_NUM_BLOCKS), Category::ServerToClient);
    }

    #[test]
    fn client_to_server_range() {
        assert_eq!(category_of(TYPE_FANOUT_INDEX), Category::ClientToServer);
    }

    #[test]
    fn boundaries() {
        // Sentinel values themselves are not categorized as their own range.
        assert_eq!(category_of(TYPE_SERVER_TO_CLIENT), Category::Error);
        assert_eq!(category_of(TYPE_CLIENT_TO_SERVER), Category::Error);
        assert_eq!(category_of(TYPE_ERROR), Category::Error);
    }

    #[test]
    fn tl_round_trip() {
        let raw = to_tl(TYPE_FANOUT_SIZE, 4);
        assert_eq!(raw & 0x8000_0000, 0x8000_0000);
        assert_eq!(tl_from(raw), (TYPE_FANOUT_SIZE, 4));
    }

    /// to_tl/tl_from must produce the exact bytes the wire expects:
    /// big-endian (type<<16 | length).
    #[test]
    fn wire_byte_layout() {
        let raw = to_tl(TYPE_FANOUT_SIZE, 4); // 0x80030004
        assert_eq!(raw, 0x80030004);
        let bytes = raw.to_be_bytes();
        assert_eq!(bytes, [0x80, 0x03, 0x00, 0x04]);
    }

    /// Mirrors Go's TypeOf for the unused-gap region (0x8006..=0xC005):
    /// these classify as ServerToClient because they are > the SC sentinel
    /// and < the CS sentinel. Go and Rust must agree.
    #[test]
    fn unused_gap_is_server_to_client() {
        assert_eq!(category_of(0x8006), Category::ServerToClient);
        assert_eq!(category_of(0xC005), Category::ServerToClient);
    }

    #[test]
    fn unused_high_is_client_to_server() {
        // 0xC008..=0xFFFE: > ClientToServer sentinel, < Error.
        assert_eq!(category_of(0xC008), Category::ClientToServer);
        assert_eq!(category_of(0xFFFE), Category::ClientToServer);
    }

    /// Bytes that came off the wire are big-endian. Confirm a complete
    /// round-trip from network bytes through tl_from.
    #[test]
    fn from_wire_bytes_round_trip() {
        let wire: [u8; 4] = [0x80, 0x03, 0x00, 0x04];
        let raw = u32::from_be_bytes(wire);
        let (typ, len) = tl_from(raw);
        assert_eq!(typ, TYPE_FANOUT_SIZE);
        assert_eq!(len, 4);
    }

    /// A bare block index (high bit clear) carries no length on the wire.
    #[test]
    fn block_index_carries_no_length() {
        let wire: [u8; 4] = [0x00, 0x00, 0x00, 0x05];
        let raw = u32::from_be_bytes(wire);
        let (typ, len) = tl_from(raw);
        assert_eq!(typ, TYPE_BLOCK_INDEX);
        assert_eq!(len, 0);
        // The actual block index value is `raw` itself (high bit clear).
        assert_eq!(raw, 5);
    }

    /// Largest legal block index (high bit must remain unset).
    #[test]
    fn max_block_index_value() {
        let raw = 0x7FFF_FFFFu32; // largest with high bit clear
        let (typ, len) = tl_from(raw);
        assert_eq!(typ, TYPE_BLOCK_INDEX);
        assert_eq!(len, 0);
    }

    /// Smallest TLV (high bit set, type sentinel).
    #[test]
    fn min_tlv_value() {
        let raw = 0x8000_0000u32; // type=0x8000, len=0
        let (typ, len) = tl_from(raw);
        assert_eq!(typ, 0x8000);
        assert_eq!(len, 0);
        // 0x8000 itself is in the Error category (it's not strictly > the
        // ServerToClient sentinel 0x8001).
        assert_eq!(category_of(typ), Category::Error);
    }

    /// to_tl handles max length (u16::MAX) without overflow into type bits.
    #[test]
    fn to_tl_max_length() {
        let raw = to_tl(TYPE_FANOUT_SIZE, 0xFFFF);
        assert_eq!(raw, 0x8003_FFFF);
        let (typ, len) = tl_from(raw);
        assert_eq!(typ, TYPE_FANOUT_SIZE);
        assert_eq!(len, 0xFFFF);
    }

    /// Real on-the-wire bytes for the testimonyd handshake reply: the four
    /// TLVs the server sends after the version byte.
    #[test]
    fn handshake_wire_bytes_match_legacy_daemon() {
        // FanoutSize(u32) — TL = 0x80030004, value 1.
        let fanout_size = to_tl(TYPE_FANOUT_SIZE, 4).to_be_bytes();
        assert_eq!(fanout_size, [0x80, 0x03, 0x00, 0x04]);
        // BlockSize TL = 0x80040004.
        let block_size = to_tl(TYPE_BLOCK_SIZE, 4).to_be_bytes();
        assert_eq!(block_size, [0x80, 0x04, 0x00, 0x04]);
        // NumBlocks TL = 0x80050004.
        let num_blocks = to_tl(TYPE_NUM_BLOCKS, 4).to_be_bytes();
        assert_eq!(num_blocks, [0x80, 0x05, 0x00, 0x04]);
        // WaitingForFanoutIndex TL = 0x80020000 (no value).
        let waiting = to_tl(TYPE_WAITING_FOR_FANOUT_INDEX, 0).to_be_bytes();
        assert_eq!(waiting, [0x80, 0x02, 0x00, 0x00]);
    }

    /// Real on-the-wire bytes for the client's reply (FanoutIndex = 0).
    #[test]
    fn client_handshake_wire_bytes() {
        let tl = to_tl(TYPE_FANOUT_INDEX, 4).to_be_bytes();
        assert_eq!(tl, [0xC0, 0x07, 0x00, 0x04]);
    }
}
